name: 🔨 pip-test
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "C:\00PackageManager\"
        $env:SCOOP='C:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH

    - name: 'Cache Scoop Packages'
      uses: actions/cache@v4
      with:
        path: C:\00PackageManager\Scoop\cache
        key: ${{ runner.os }}-scoop-cache

    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k git aria2 sudo 7zip biome jq yq vim curl wget base64 gawk grep sed
        scoop install -k python
        scoop cleanup *
        scoop cache rm *
        scoop cleanup -k *

    - name: 'Downloads pip Packages'
      shell: pwsh
      run: |
        pip install sqlmap bs4 XlsxWriter tqdm python-libnmap pyDes pipx openpyxl rncryptor

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' a -mx9 -t7z 'C:\00PackageManager.7z' 'C:\00PackageManager\*'
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' l 'C:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager
        path: C:\00PackageManager.7z
