name: 🔨 Scooparchive
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Set up Scoop'
      shell: pwsh
      run: |
        mkdir "C:\00PackageManager\"
        $env:SCOOP='C:\00PackageManager\Scoop'
        [Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser 
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop bucket add versions
        scoop bucket add nirsoft
        scoop bucket add java
        scoop bucket add nonportable
        scoop bucket add ktools https://github.com/kenyon-wong/ktools
        
        echo "$env:SCOOP\shims" >> $env:GITHUB_PATH

    - name: 'Install Required Tools'
      shell: pwsh 
      run: |
        scoop install -k git aria2 sudo 7zip biome jq yq vim curl wget base64 gawk grep sed cwrsync cacert openssl autocorrect
        scoop install -k liberica8-full-jdk liberica11-full-jdk liberica17-full-jdk liberica-full-jdk 
        scoop install -k gradle maven jenv idea-ultimate jadx
        scoop install -k python
        scoop install -k codeql osv-scanner
        scoop install -k burp-suite-pro-np
        scoop install -k sublime-text vscode redis-desktop-manager obsidian
        scoop install -k windowsdesktop-runtime-lts windows-terminal
        scoop install -k firefox googlechrome
        scoop install -k keepassxc openark kubectl sslscan sqlitestudio keepass-plugin-keepassrpc
        scoop install -k dupeGuru dismplusplus renamer everything powertoys TrafficMonitor snipaste vncviewer sysinternals
        scoop install -k gogo spray zombie fscan
        scoop cleanup *
        scoop cache rm *
        scoop cleanup -k *
        scoop list

    - name: 'Downloads Pip Packages'
      shell: pwsh
      run: |
        echo "C:\00PackageManager\Scoop\apps\python\current\Scripts" >> $GITHUB_PATH
        $env:SCOOPpy='C:\00PackageManager\Scoop\apps\python\current\python.exe'
        & $env:SCOOPpy -m pip install --upgrade pip
        & $env:SCOOPpy -m pip -V
        & $env:SCOOPpy -m pip install sqlmap bs4 XlsxWriter tqdm python-libnmap pyDes pipx openpyxl tldextract
        & $env:SCOOPpy -m pip install colorama rncryptor pandas requests pycryptodome beautifulsoup4 chardet
        git clone --depth 1 https://github.com/r0oth3x49/ghauri.git C:\00PackageManager\ghauri
        & $env:SCOOPpy -m pip freeze

    - name: 'Clone CodeQL Repository'
      shell: pwsh
      run: |
        git clone --depth 1 https://github.com/github/codeql.git C:\00PackageManager\CodeqlRules
        git clone --recursive https://github.com/github/vscode-codeql-starter.git C:\00PackageManager\vscode-codeql-starter
        tree /f C:\00PackageManager\codeqlRules

    - name: 'Compress Scoop Directory'
      shell: pwsh
      run: |
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' a -mx9 -t7z 'C:\00PackageManager.7z' 'C:\00PackageManager\*'
        & 'C:\00PackageManager\Scoop\apps\7zip\current\7z.exe' l 'C:\00PackageManager.7z'

    - name: 'Upload Compressed Scoop Directory'
      uses: actions/upload-artifact@v4
      with:
        name: Scoop-00PackageManager
        path: C:\00PackageManager.7z
        retention-days: 3
        compression-level: 0
